{% set name = "XCDF" %}
{% set version = "v3.00.03" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jimbraun/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 4e445a2fea947ba14505d08177c8d5b55856f8411f28de1fe4d4c00f6824b711

build:
  number: 0
  skip: True  # [py3k or win]

requirements:
  build:
    # - {{ compiler('c') }}
    # - {{ compiler('cxx') }}
    - cmake
  host:
    - zlib

test:
about:
  home: https://github.com/jimbraun/XCDF
  license_file: LICENSE
  summary: 'XCDF: The eXplicitly Compacted Data Format'
  description: |
    The eXplicitly Compacted Data Format (XCDF) is written and maintained by Jim
    Braun at the University of Maryland.  XCDF is a binary data format designed
    to store data fields with a user-specified accuracy.  The library uses
    bit-packing to store the field at the given accuracy for a given set of
    values, and therefore provides substantial compression.
    Python bindings for XCDF are written and maintained by Segev BenZvi at the
    University of Wisconsin-Madison.

extra:
  recipe-maintainers:
    - ColasRi
